"""initial_tables

Revision ID: 8998edfc8cee
Revises: 
Create Date: 2025-07-16 21:27:26.705664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8998edfc8cee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('from_currency', sa.String(length=3), nullable=True),
    sa.Column('to_currency', sa.String(length=3), nullable=True),
    sa.Column('from_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('to_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_transactions_id'), 'conversion_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_transactions_user_id'), 'conversion_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversion_transactions_user_id'), table_name='conversion_transactions')
    op.drop_index(op.f('ix_conversion_transactions_id'), table_name='conversion_transactions')
    op.drop_table('conversion_transactions')
    # ### end Alembic commands ###
